backend:
  name: github
  branch: master
  repo: minuscode/jordiburch

media_folder: "/public/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: src/pages/Projetos
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "project"}
      - { name: title, label: Title }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - { name: image, label: Image, widget: image, required: false }
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "path", label: "Path"}
