backend:
  name: git-gateway
  branch: cms-organization
  repo: minuscode/jordiburch

media_folder: "/public/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:  
  - name: preview-group
    label: Preview Groups
    label_singular: Preview Group
    folder: src/pages/PreviewGroup
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "previewGroupTemplate"}
      - { name: title, label: Title }
      - { name: "path", label: "Path Name" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: image, label: Cover Image, widget: image}
      - { name: "body", label: "Body", widget: "markdown", required: false}
      - { name: "featured", label: "Show on Homepage", widget: "select", options: ["Yes", "No"], default: "No" }

  - name: text-posts
    label: Text Posts
    label_singular: Text Post
    folder: src/pages/TextPost
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "textPostTemplate"}
      - { name: title, label: Title }
      - { name: "path", label: "Path Name" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: image, label: Cover Image, widget: image}
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "featured", label: "Show on Homepage", widget: "select", options: ["Yes", "No"], default: "No" }

  - name: image-posts
    label: Image Posts
    label_singular: Image Post
    folder: src/pages/ImagePost
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "imagePostTemplate"}
      - { name: title, label: Title }
      - { name: "path", label: "Path Name" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: image, label: Image, widget: image }
      - {label: "Description", name: "description", widget: "markdown", required: false}
      - { name: "featured", label: "Show on Homepage", widget: "select", options: ["Yes", "No"], default: "No" }
    
  - name: image-text-posts
    label: Image and Text Posts
    label_singular: Image and Text Post
    folder: src/pages/ImageTextPost 
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "imagetextPostTemplate"}
      - { name: title, label: Title }
      - { name: "path", label: "Path Name" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: image, label: Cover Image, widget: image }
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "featured", label: "Show on Homepage", widget: "select", options: ["Yes", "No"], default: "No" }

  - name: cv
    label: Curriculum Vitae
    label_singular: Curriculum Vitae
    folder: src/pages/cv
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "cv"}
      - { name: title, label: Title }
      - { name: "path", label: "Path Name" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: "body", label: "Body", widget: "markdown"}
