backend:
  name: github
  branch: cms-organization
  repo: minuscode/jordiburch

media_folder: "/public/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: src/pages/Projetos
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "project"}
      - { name: title, label: Title }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: image, label: Image, widget: image, required: false }
      - { name: "body", label: "Body", widget: "markdown", required: false}
      - { name: "path", label: "Path Name", default: "/projetos/" }

  - name: texts
    label: Texts
    label_singular: Text
    folder: src/pages/Textos
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "text"}
      - { name: title, label: Title }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: image, label: Image, widget: image, required: false }
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "path", label: "Path Name", default: "/textos/" }

  - name: books
    label: Books
    label_singular: Book
    folder: src/pages/Livros
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "book"}
      - { name: title, label: Title }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: image, label: Image, widget: image, required: false }
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "path", label: "Path Name", default: "/livros/" }

  - name: exhibitions
    label: Exhibitions
    label_singular: Exhibition
    folder: src/pages/Exposicoes
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "exhibition"}
      - { name: title, label: Title }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - { name: image, label: Image, widget: image, required: false }
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "path", label: "Path Name", default: "/livros/" }
