backend:
  name: github
  branch: master
  repo: minuscode/jordiburch

media_folder: "/public/assets/images/uploads"
public_folder: "/assets/images/uploads"

publish_mode: editorial_workflow
collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: src/pages/Projetos
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "project"}
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image, required: false }
      - { name: "body", label: "Body", widget: "markdown"}
